version: "3"

services:
  db:
    container_name: postgresql
    restart: always
    image: psql
    build:
      context: postgres/
    networks:
      - default
    expose:
      - 5432
    ports:
      - 5432:5432
  price-monitoring:
    build: app
    depends_on:
      - db
    container_name: app
    restart: always
    ports:
      - "9000:9000"
    networks:
      - default